<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHJhdyDD\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHJhdyDD/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHJhdyDD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHJhdyDD\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHJhdyDD\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HJhdyDD',
    'container.build_id' => '1a45c203',
    'container.build_time' => 1573366540,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHJhdyDD');
